scc: scc_finder.cc
	g++ -std=c++11 -march=native -Wall -O4 scc_finder.cc -o sccfinder

rg: random_graph.cc
	g++ -std=c++11 -march=native -Wall -O4 random_graph.cc -o randomgraph

clean:
	rm -f sccfinder randomgraph
